name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs: 
  getCode:
    runs-on: self-hosted
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: |
        export NODE_OPTIONS="--max-old-space-size=8192"
        npm ci
        cd frontend
        npm i
  build:
    runs-on: self-hosted
    steps: 
    - run: |
        cd frontend
        npm run build
        cd ..
        pm2 stop 0
        pm2 start 0
        pm2 save
        sudo service nginx restart