name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs: 
  getCode:
    runs-on: self-hosted
    steps:
    - name: Get Code
      uses: actions/checkout@v3
    - run: |
        npm ci
        cd frontend
        npm ci
        npm run build
